name: pre-commit

on:
  pull_request:
  push:
    branches: [master, main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Install fuse
    - name: Install fuse
      run: |
          sudo apt-get update
          sudo apt-get install -y fuse3 libfuse3-dev
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
